import { z } from "zod";

const metricSummarySchema = z.object({
  mean: z.number(),
  std: z.number(),
  ci95_low: z.number(),
  ci95_high: z.number(),
  min: z.number(),
  max: z.number(),
  n: z.number(),
});

const testSchema = z.object({
  test: z.string(),
  statistic: z.number(),
}).passthrough();

export const aggregateSchema = z.object({
  protocol: z.literal("full"),
  seeds: z.array(z.number()).length(5),
  n_seeds: z.number(),
  confidence_interval: z.string(),
  contextual_bandit_reward: metricSummarySchema,
  contextual_bandit_approved_value: metricSummarySchema,
  contextual_bandit_detection_rate: metricSummarySchema,
  contextual_bandit_no_novelty_reward: metricSummarySchema,
  random_reward: metricSummarySchema,
  rule_mutation_reward: metricSummarySchema,
  v0_held_out_auc: metricSummarySchema,
  v0_held_out_precision: metricSummarySchema,
  v0_held_out_recall: metricSummarySchema,
  v0_held_out_fpr: metricSummarySchema,
  v0_fresh_reward: metricSummarySchema,
  v0_fresh_approved_value: metricSummarySchema,
  v1_held_out_auc: metricSummarySchema,
  v1_held_out_precision: metricSummarySchema,
  v1_held_out_recall: metricSummarySchema,
  v1_held_out_fpr: metricSummarySchema,
  v1_fresh_reward: metricSummarySchema,
  v1_fresh_approved_value: metricSummarySchema,
  v2_held_out_auc: metricSummarySchema,
  v2_held_out_precision: metricSummarySchema,
  v2_held_out_recall: metricSummarySchema,
  v2_held_out_fpr: metricSummarySchema,
  v2_fresh_reward: metricSummarySchema,
  v2_fresh_approved_value: metricSummarySchema,
  fresh_value_reduction_v0_to_v1: metricSummarySchema,
  fresh_value_reduction_v1_to_v2: metricSummarySchema,
  novelty_ablation_reward_delta: metricSummarySchema,
  significance_tests: z.object({
    bandit_vs_random: testSchema,
    bandit_vs_rule: testSchema,
    novelty_on_vs_off: testSchema,
    v1_vs_v0_fresh_reward: testSchema,
    v2_vs_v1_fresh_reward: testSchema,
  }),
}).passthrough();

const numeric = z.coerce.number();
const csvBoolean = z.preprocess(
  (value) => value === true || String(value).toLowerCase() === "true",
  z.boolean(),
);

export const seedResultSchema = z.object({
  seed: numeric,
  protocol: z.literal("full"),
  contextual_bandit_reward: numeric,
  contextual_bandit_approved_value: numeric,
  contextual_bandit_detection_rate: numeric,
  contextual_bandit_no_novelty_reward: numeric,
  random_reward: numeric,
  random_approved_value: numeric,
  random_detection_rate: numeric,
  rule_mutation_reward: numeric,
  rule_mutation_approved_value: numeric,
  rule_mutation_detection_rate: numeric,
  v0_held_out_auc: numeric,
  v0_held_out_precision: numeric,
  v0_held_out_recall: numeric,
  v0_held_out_fpr: numeric,
  v0_fresh_reward: numeric,
  v0_fresh_approved_value: numeric,
  v1_held_out_auc: numeric,
  v1_held_out_precision: numeric,
  v1_held_out_recall: numeric,
  v1_held_out_fpr: numeric,
  v1_fresh_reward: numeric,
  v1_fresh_approved_value: numeric,
  v2_held_out_auc: numeric,
  v2_held_out_precision: numeric,
  v2_held_out_recall: numeric,
  v2_held_out_fpr: numeric,
  v2_fresh_reward: numeric,
  v2_fresh_approved_value: numeric,
  novelty_ablation_reward_delta: numeric,
}).passthrough();

export const attackCardSchema = z.object({
  family: z.string(),
  title: z.string(),
  variants: z.array(z.string()).length(4),
  channel: z.string(),
  rail: z.string(),
  genai_enabler: z.string(),
  objective: z.string(),
  event_sequence: z.array(z.string()),
  amount_range: z.tuple([z.number(), z.number()]),
  event_range: z.tuple([z.number(), z.number()]),
  base_risk: z.number(),
  device_reuse: z.number(),
  beneficiary_reuse: z.number(),
  merchant_risk: z.number(),
  velocity: z.number(),
  novelty: z.number(),
  mitigations: z.array(z.string()),
});

export const calibrationSchema = z.object({
  calibration_split: z.string(),
  evaluation_split: z.string(),
  legitimate_split_rows: z.object({ train: z.number(), validation: z.number(), test: z.number() }),
  event_id_overlap_validation_test: z.number(),
  known_campaign_overlap_train_validation: z.number(),
  known_campaign_overlap_validation_test: z.number(),
  held_out_campaigns_generated_separately: z.boolean(),
  thresholds: z.record(z.string(), z.object({
    source: z.string(),
    legitimate_rows: z.number(),
    target_fpr: z.number(),
    empirical_validation_fpr: z.number(),
    threshold: z.number(),
  })),
  test_rows_used_for_threshold_selection: z.boolean(),
});

export const prevalenceRowSchema = z.object({
  defender: z.enum(["V0", "V1", "V2"]),
  scenario: z.string(),
  prevalence: numeric,
  fraud_rows: numeric,
  legitimate_rows: numeric,
  repetitions: numeric,
  roc_auc_mean: numeric,
  roc_auc_ci_low: z.union([numeric, z.literal("")]).optional(),
  roc_auc_ci_high: z.union([numeric, z.literal("")]).optional(),
  pr_auc_mean: numeric,
  precision_mean: numeric,
  precision_ci_low: z.union([numeric, z.literal("")]).optional(),
  precision_ci_high: z.union([numeric, z.literal("")]).optional(),
  recall_mean: numeric,
  fpr_mean: numeric,
});

export const diagnosticRowSchema = z.object({
  artifact_version: z.string(),
  iteration: numeric,
  strategy: z.string(),
  action_id: z.string(),
  family: z.string(),
  reward: numeric,
  fidelity: numeric,
  valid: csvBoolean,
  approved_value: numeric,
  detection_rate: numeric,
  mean_risk_score: numeric,
  event_count: numeric,
  novel_evasion: csvBoolean,
  value_term: numeric,
  evasion_term: numeric,
  detection_cost_term: numeric,
  resource_cost_term: numeric,
  novelty_term: numeric,
  validity_term: numeric,
  pre_fidelity_reward: numeric,
  seed: numeric,
  generation: z.literal("V2"),
  protocol: z.literal("full"),
  seed_campaigns: numeric,
  seed_valid_campaigns: numeric,
  seed_fully_detected_campaigns: numeric,
  seed_mean_fidelity: numeric,
  seed_min_fidelity: numeric,
  seed_median_fidelity: numeric,
  seed_max_fidelity: numeric,
  seed_unique_actions: numeric,
}).passthrough();

const fidelitySchema = z.object({
  valid: z.literal(true),
  score: z.number(),
  schema_score: z.number(),
  range_score: z.number(),
  temporal_score: z.number(),
  graph_score: z.number(),
  behavioural_score: z.number(),
  reasons: z.array(z.string()),
});

const campaignEventSchema = z.object({
  event_id: z.string(),
  campaign_id: z.string(),
  timestamp: z.string(),
  customer_id: z.string(),
  device_id: z.string(),
  merchant_id: z.string(),
  beneficiary_id: z.string(),
  channel: z.string(),
  rail: z.string(),
  amount: z.number(),
  device_reuse_24h: z.number(),
  beneficiary_reuse_24h: z.number(),
  velocity_10m: z.number(),
  velocity_1h: z.number(),
  intent_match: z.number(),
  graph_degree: z.number(),
  graph_shared_entities: z.number(),
  sequence_stage: z.string(),
  rollout_index: z.number(),
}).passthrough();

export const representativeCampaignSchema = z.object({
  artifact_version: z.string(),
  artifact_type: z.literal("representative_campaign_rollout"),
  evidence_boundary: z.string(),
  selection_note: z.string(),
  generator: z.object({
    implementation: z.string(),
    simulator_design: z.literal("hand-coded_stateful_entity_linked"),
    config_path: z.string(),
    world_seed: z.number(),
    action_seed: z.number(),
    campaign_seed: z.number(),
  }),
  attack_card: attackCardSchema,
  action: z.record(z.string(), z.union([z.string(), z.number()])),
  fidelity: fidelitySchema,
  summary: z.object({
    campaign_id: z.string(),
    event_count: z.number(),
    start_timestamp: z.string(),
    end_timestamp: z.string(),
    duration_minutes: z.number(),
    unique_customers: z.number(),
    unique_devices: z.number(),
    unique_merchants: z.number(),
    unique_beneficiaries: z.number(),
    maximum_velocity_10m: z.number(),
    maximum_velocity_1h: z.number(),
    maximum_graph_shared_entities: z.number(),
  }),
  events: z.array(campaignEventSchema).min(1),
});

export type Aggregate = z.infer<typeof aggregateSchema>;
export type SeedResult = z.infer<typeof seedResultSchema>;
export type AttackCard = z.infer<typeof attackCardSchema>;
export type CalibrationAudit = z.infer<typeof calibrationSchema>;
export type PrevalenceRow = z.infer<typeof prevalenceRowSchema>;
export type DiagnosticRow = z.infer<typeof diagnosticRowSchema>;
export type RepresentativeCampaign = z.infer<typeof representativeCampaignSchema>;
