import { DefenderProgression } from "@/components/charts/defender-progression";
import { FreshValueProgression } from "@/components/charts/fresh-value-progression";
import { MetricCard } from "@/components/metric-card";
import { PageHeader } from "@/components/page-header";
import { ProvenanceChip } from "@/components/provenance-chip";
import { Alert } from "@/components/ui/alert";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { loadAggregate, loadSeedResults, loadV2Diagnostics } from "@/lib/evidence/loader";
import { format } from "@/lib/format";

export const metadata = { title: "Defend · Hardening Progression" };

export default async function DefendPage() {
  const [aggregate, seeds, diagnostics] = await Promise.all([loadAggregate(), loadSeedResults(), loadV2Diagnostics()]);
  const allValid = diagnostics.every((row) => row.valid);
  const allDetected = diagnostics.every((row) => row.detection_rate === 1);
  return <div><PageHeader eyebrow="Defend · Hardening progression" title="Adversarial campaigns become training pressure for the next defender generation." conclusion="Held-out discrimination and recall improve from V0 to V2 while the legitimate false-positive rate remains near its validation-calibrated operating point."><ProvenanceChip source="artifacts/full_multiseed/aggregate.json" field="v0/v1/v2 held_out_auc, held_out_recall, held_out_fpr" /></PageHeader><div className="grid gap-4 md:grid-cols-3"><MetricCard label="V0 held-out ROC-AUC" value={format.number(aggregate.v0_held_out_auc.mean, 5)} detail={`95% CI ${format.number(aggregate.v0_held_out_auc.ci95_low, 5)} to ${format.number(aggregate.v0_held_out_auc.ci95_high, 5)}`} source="artifacts/full_multiseed/aggregate.json" field="v0_held_out_auc" tone="blue" /><MetricCard label="V1 held-out ROC-AUC" value={format.number(aggregate.v1_held_out_auc.mean, 5)} detail={`95% CI ${format.number(aggregate.v1_held_out_auc.ci95_low, 5)} to ${format.number(aggregate.v1_held_out_auc.ci95_high, 5)}`} source="artifacts/full_multiseed/aggregate.json" field="v1_held_out_auc" tone="orange" /><MetricCard label="V2 held-out ROC-AUC" value={format.number(aggregate.v2_held_out_auc.mean, 5)} detail={`95% CI ${format.number(aggregate.v2_held_out_auc.ci95_low, 5)} to ${format.number(aggregate.v2_held_out_auc.ci95_high, 5)}`} source="artifacts/full_multiseed/aggregate.json" field="v2_held_out_auc" tone="green" /></div><div className="mt-6 grid gap-5 xl:grid-cols-3">{[["ROC-AUC","auc"],["Recall","recall"],["Legitimate FPR","fpr"]].map(([title,metric])=><Card key={metric}><CardHeader><div><CardTitle>{title}</CardTitle><CardDescription>Five seed paths plus seed-level mean.</CardDescription></div></CardHeader><CardContent><DefenderProgression rows={seeds} metric={metric as "auc"|"recall"|"fpr"} /></CardContent></Card>)}</div><Card className="mt-6"><CardHeader><div><CardTitle>Fresh-attacker approved value across generations</CardTitle><CardDescription>The boundary condition is written inside the visualization, not left to a tooltip.</CardDescription></div><ProvenanceChip source="artifacts/full_multiseed/seed_results.csv" field="v0_fresh_approved_value / v1_fresh_approved_value / v2_fresh_approved_value" /></CardHeader><CardContent><FreshValueProgression rows={seeds} /></CardContent></Card><div className="mt-6 grid gap-5 lg:grid-cols-2"><Alert title="Matched-pool V2 result" tone={allValid && allDetected ? "success" : "warning"}>Against a matched, fixed action pool held constant across generations, the hardened defender (V2) detected every campaign across five seeds.</Alert><Alert title="Directional, not conclusive" tone="warning">The V1→V2 fresh-reward comparison has one-sided p = {format.number(Number(aggregate.significance_tests.v2_vs_v1_fresh_reward.p_value_one_sided), 4)}. This is a directional stability result, not a confirmed generational claim.</Alert></div></div>;
}
